site_name: Picsellia CV Engine
repo_url: https://github.com/picselliahq/picsellia-cv-engine
site_url: https://github.com/picselliahq/picsellia-cv-engine
theme:
  name: material
  features:
    - content.tabs.link
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - announce.dismiss
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.preview
    - navigation.instant.progress
    - navigation.path
    - navigation.sections
    - navigation.top
    - navigation.tracking
    - navigation.footer
    - search.suggest
    - toc.follow
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: lime
      toggle:
        icon: material/weather-night
        name: Switch to system preference

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage Guide:
      - Overview: usage/index.md
      - Training:
          - Simple Template: usage/training/simple.md
      - Processing:
          - Simple Template: usage/processing/simple.md
  - API Reference:
      - Overview: api/index.md
      - Core:
          - Contexts:
              - Common:
                  - Picsellia Context: api/core/contexts/common/picsellia_context.md
              - Processing:
                  - Datalake:
                      - Local Datalake Processing Context: api/core/contexts/processing/datalake/local_datalake_processing_context.md
                      - Picsellia Datalake Processing Context: api/core/contexts/processing/datalake/picsellia_datalake_processing_context.md
                  - Dataset:
                      - Local Processing Context: api/core/contexts/processing/dataset/local_processing_context.md
                      - Picsellia Dataset Processing Context: api/core/contexts/processing/dataset/picsellia_dataset_processing_context.md
                      - Picsellia Processing Context: api/core/contexts/processing/dataset/picsellia_processing_context.md
                  - Model:
                      - Picsellia Model Processing Context: api/core/contexts/processing/model/picsellia_model_processing_context.md
              - Training:
                  - Local Training Context: api/core/contexts/training/local_training_context.md
                  - Picsellia Training Context: api/core/contexts/training/picsellia_training_context.md
          - Data:
              - Datalake:
                  - Datalake: api/core/data/datalake/datalake.md
                  - Datalake Collection: api/core/data/datalake/datalake_collection.md
              - Dataset:
                  - Base Dataset: api/core/data/dataset/base_dataset.md
                  - Coco Dataset: api/core/data/dataset/coco_dataset.md
                  - Dataset Collection: api/core/data/dataset/dataset_collection.md
                  - Utils: api/core/data/dataset/utils.md
                  - Yolo Dataset: api/core/data/dataset/yolo_dataset.md
          - Models:
              - Model: api/core/models/model.md
              - Model Collection: api/core/models/model_collection.md
              - Model Downloader: api/core/models/model_downloader.md
              - Picsellia Prediction: api/core/models/picsellia_prediction.md
          - Parameters:
              - Augmentation Parameters: api/core/parameters/augmentation_parameters.md
              - Base Parameters: api/core/parameters/base_parameters.md
              - Export Parameters: api/core/parameters/export_parameters.md
              - Hyper Parameters: api/core/parameters/hyper_parameters.md
          - Services:
              - Data:
                  - Dataset:
                      - Loader:
                          - Training Dataset Collection Extractor: api/core/services/data/dataset/loader/training_dataset_collection_extractor.md
                      - Preprocessing:
                          - Classification Dataset Preparator: api/core/services/data/dataset/preprocessing/classification_dataset_preparator.md
                      - Uploader:
                          - Classification:
                              - Coco Classification Dataset Uploader: api/core/services/data/dataset/uploader/classification/coco_classification_dataset_uploader.md
                          - Common:
                              - Data Uploader: api/core/services/data/dataset/uploader/common/data_uploader.md
                              - Dataset Uploader: api/core/services/data/dataset/uploader/common/dataset_uploader.md
                          - Object_Detection:
                              - Coco Object Detection Dataset Uploader: api/core/services/data/dataset/uploader/object_detection/coco_object_detection_dataset_uploader.md
                          - Segmentation:
                              - Coco Segmentation Dataset Uploader: api/core/services/data/dataset/uploader/segmentation/coco_segmentation_dataset_uploader.md
                          - Utils: api/core/services/data/dataset/uploader/utils.md
                      - Utils: api/core/services/data/dataset/utils.md
                      - Validator:
                          - Classification:
                              - Coco Classification Dataset Context Validator: api/core/services/data/dataset/validator/classification/coco_classification_dataset_context_validator.md
                          - Common:
                              - Dataset Collection Validator: api/core/services/data/dataset/validator/common/dataset_collection_validator.md
                              - Dataset Validator: api/core/services/data/dataset/validator/common/dataset_validator.md
                              - Not Configured Dataset Validator: api/core/services/data/dataset/validator/common/not_configured_dataset_validator.md
                          - Object_Detection:
                              - Coco Object Detection Dataset Validator: api/core/services/data/dataset/validator/object_detection/coco_object_detection_dataset_validator.md
                              - Yolo Object Detection Dataset Validator: api/core/services/data/dataset/validator/object_detection/yolo_object_detection_dataset_validator.md
                          - Segmentation:
                              - Coco Segmentation Dataset Validator: api/core/services/data/dataset/validator/segmentation/coco_segmentation_dataset_validator.md
                              - Yolo Segmentation Dataset Validator: api/core/services/data/dataset/validator/segmentation/yolo_segmentation_dataset_validator.md
                          - Utils: api/core/services/data/dataset/validator/utils.md
              - Model:
                  - Evaluator:
                      - Model Evaluator: api/core/services/model/evaluator/model_evaluator.md
                      - Utils:
                          - Coco Converter: api/core/services/model/evaluator/utils/coco_converter.md
                          - Coco Utils: api/core/services/model/evaluator/utils/coco_utils.md
                          - Compute Confusion Matrix: api/core/services/model/evaluator/utils/compute_confusion_matrix.md
                  - Export:
                      - Model Exporter: api/core/services/model/export/model_exporter.md
                  - Predictor:
                      - Model Collection Predictor: api/core/services/model/predictor/model_collection_predictor.md
                      - Model Predictor: api/core/services/model/predictor/model_predictor.md
                  - Utils: api/core/services/model/utils.md
              - Processing:
                  - Dataset Version Creation Processing: api/core/services/processing/dataset_version_creation_processing.md
              - Utils:
                  - Dataset Logging: api/core/services/utils/dataset_logging.md
                  - Image File: api/core/services/utils/image_file.md
                  - Local Context: api/core/services/utils/local_context.md
                  - Picsellia Context: api/core/services/utils/picsellia_context.md
          - Step Metadata: api/core/step_metadata.md
      - Decorators:
          - Pipeline Decorator: api/decorators/pipeline_decorator.md
          - Step Decorator: api/decorators/step_decorator.md
          - Step Metadata: api/decorators/step_metadata.md
      - Frameworks:
          - Ultralytics:
              - Model:
                  - Model: api/frameworks/ultralytics/model/model.md
              - Parameters:
                  - Augmentation Parameters: api/frameworks/ultralytics/parameters/augmentation_parameters.md
                  - Hyper Parameters: api/frameworks/ultralytics/parameters/hyper_parameters.md
              - Services:
                  - Data:
                      - Utils: api/frameworks/ultralytics/services/data/utils.md
                  - Model:
                      - Callbacks: api/frameworks/ultralytics/services/model/callbacks.md
                      - Exporter: api/frameworks/ultralytics/services/model/exporter.md
                      - Logger:
                          - Base: api/frameworks/ultralytics/services/model/logger/base.md
                          - Classification: api/frameworks/ultralytics/services/model/logger/classification.md
                          - Object Detection: api/frameworks/ultralytics/services/model/logger/object_detection.md
                          - Segmentation: api/frameworks/ultralytics/services/model/logger/segmentation.md
                      - Predictor:
                          - Classification: api/frameworks/ultralytics/services/model/predictor/classification.md
                          - Object Detection: api/frameworks/ultralytics/services/model/predictor/object_detection.md
                          - Segmentation: api/frameworks/ultralytics/services/model/predictor/segmentation.md
                      - Trainer: api/frameworks/ultralytics/services/model/trainer.md
                      - Utils: api/frameworks/ultralytics/services/model/utils.md
      - Steps:
          - Base:
              - Datalake:
                  - Loader: api/steps/base/datalake/loader.md
              - Dataset:
                  - Loader: api/steps/base/dataset/loader.md
                  - Preprocessor: api/steps/base/dataset/preprocessor.md
                  - Uploader: api/steps/base/dataset/uploader.md
                  - Validator: api/steps/base/dataset/validator.md
              - Model:
                  - Builder: api/steps/base/model/builder.md
                  - Evaluator: api/steps/base/model/evaluator.md
          - Ultralytics:
              - Dataset:
                  - Preparator: api/steps/ultralytics/dataset/preparator.md
              - Model:
                  - Evaluator: api/steps/ultralytics/model/evaluator.md
                  - Exporter: api/steps/ultralytics/model/exporter.md
                  - Loader: api/steps/ultralytics/model/loader.md
                  - Trainer: api/steps/ultralytics/model/trainer.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths:
            - .
          options:
            members_order: source
            docstring_style: google
            docstring_options:
              ignore_init_summary: true
            docstring_section_style: table
            show_docstring_raises: false
            filters:
              - '!^_'
              - '!^T'
              - '!^logger$'
              - "!^BATCH_SIZE$"
            heading_level: 2
            inherited_members: true
            merge_init_into_class: true
            parameter_headings: true
            preload_modules:
              - mkdocstrings
            relative_crossrefs: true
            scoped_crossrefs: true
            separate_signature: false
            show_bases: true
            show_inheritance_diagram: true
            show_root_heading: true
            show_root_full_path: false
            show_signature_annotations: false
            show_source: false
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            show_if_no_docstring: false
            summary: true
            unwrap_annotated: true
            group_by_category: true
            extra:
              module: picsellia_cv_engine
markdown_extensions:
  - attr_list
  - admonition
  - tables
  - toc:
      permalink: true
      title: Page contents
      toc_depth: 2
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      pygments_lang_class: true
  - pymdownx.extra
  - pymdownx.tabbed:
      alternate_style: true
